-- Chuyen session ve CDB
ALTER SESSION SET CONTAINER=CDB$ROOT;
-- Tao common user
CREATE USER C##ADMIN IDENTIFIED BY "123";
-- Cho phep user ket noi toi CDB
GRANT CREATE SESSION TO C##ADMIN;

-- Chuyen session ve PDB ATTT
ALTER SESSION SET CONTAINER=ATTT;
-- Cho phep user ket noi toi CDB
GRANT CREATE SESSION TO C##ADMIN;

-- Cap cac quyen DBA, VPD va OLS
GRANT ALTER USER TO C##ADMIN WITH ADMIN OPTION;
GRANT CREATE USER TO C##ADMIN WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO C##ADMIN WITH ADMIN OPTION;
GRANT DROP USER TO C##ADMIN WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO C##ADMIN WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO C##ADMIN WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO C##ADMIN WITH ADMIN OPTION;
GRANT DBA TO C##ADMIN WITH ADMIN OPTION;
GRANT SYSDBA TO C##ADMIN WITH ADMIN OPTION;
GRANT ALL PRIVILEGES TO C##ADMIN WITH ADMIN OPTION;
GRANT EXECUTE ON DBMS_RLS TO C##ADMIN;
GRANT EXECUTE ON DBMS_CRYPTO TO C##ADMIN;
GRANT EXECUTE ON dbms_fga TO C##ADMIN;