ALTER SESSION SET CONTAINER=ATTT;
-- DROP ROLE
DROP ROLE RL_NVCOBAN;
DROP ROLE RL_GIANGVIEN;
DROP ROLE RL_GIAOVU;
DROP ROLE RL_TRUONGDV;
DROP ROLE RL_TRUONGKHOA;
DROP ROLE RL_SINHVIEN;

-- CREATE ROLE
CREATE ROLE RL_NVCOBAN;
CREATE ROLE RL_GIANGVIEN;
CREATE ROLE RL_GIAOVU;
CREATE ROLE RL_TRUONGDV;
CREATE ROLE RL_TRUONGKHOA;
CREATE ROLE RL_SINHVIEN;

-- DROP USERS
EXEC USP_DROP_LIST_USERS;

-- CREATE USERS
EXEC USP_CREATE_LIST_USERS;