BEGIN
SA_SYSDBA.DROP_POLICY(
    policy_name => 'BRANCH_POLICY'
);
END;
/

--B12: TẠO CHÍNH SÁCH OLS 
BEGIN 
    SA_SYSDBA.CREATE_POLICY( 
        policy_name => 'BRANCH_POLICY', 
        column_name => 'BRANCH_LABEL'
    ); 
END; 
/ 

--B13: ENABLE POLICY VỪA TẠO 
EXEC SA_SYSDBA.ENABLE_POLICY ('BRANCH_POLICY');

--B14: KHỞI ĐỘNG LẠI MÁY TÍNH 
--B15: TẠO COMPONENT CỦA LABEL
--Tao Level
EXECUTE SA_COMPONENTS.CREATE_LEVEL('BRANCH_POLICY',100,'SINHVIEN','Sinh vien'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('BRANCH_POLICY',200,'NVCOBAN','Nhan vien co ban'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('BRANCH_POLICY',300,'GIAOVU','Giao vu');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('BRANCH_POLICY',400,'GIANGVIEN','Giang vien'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('BRANCH_POLICY',500,'TRUONGDV','Truong don vi'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('BRANCH_POLICY',600,'TRUONGKHOA','Truong khoa'); 

--Tao Compartment 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',110,'VPK','Van phong khoa'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',120,'HTTT','Bo mon HTTT');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',130,'CNPM','Bo mon CNPM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',140,'KHMT','Bo mon KHMT'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',150,'CNTT','Bo mon CNTT'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',160,'TGMT','Bo mon TGMT'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('BRANCH_POLICY',170,'MMT','Bo mon MMT va Vien thong'); 

--Tao Group
EXECUTE SA_COMPONENTS.CREATE_GROUP('BRANCH_POLICY',10,'CS1','Co so 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('BRANCH_POLICY',20,'CS2','Co so 2'); 

--B16:CẤP QUYỀN CHO ADMIN TRÊN OLS POLICY 
EXECUTE SA_USER_ADMIN.SET_USER_PRIVS('BRANCH_POLICY','OLS_ADMIN','FULL,PROFILE_ACCESS');