-- Run with OLS_ADMIN --
EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','THONGBAO');
EXECUTE SA_POLICY_ADMIN.APPLY_TABLE_POLICY (policy_name => 'BRANCH_POLICY', schema_name => 'C##ADMIN', table_name => 'THONGBAO', table_options => 'NO_CONTROL'); 
--DESC C##ADMIN.THONGBAO;

--SELECT  CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV::CS1,CS2') FROM DUAL;
--B19: CẬP NHẬT NHÃN CHO CÁC DÒNG TRONG BẢNG (ĐANG DÙNG CẬP NHẬT THỦ CÔNG) 
ALTER SESSION SET nls_date_format='dd-mm-yyyy';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGKHOA') WHERE NGAY = '01-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV::CS2') WHERE NGAY = '02-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'GIAOVU') WHERE NGAY = '03-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV') WHERE NGAY = '04-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'SINHVIEN:HTTT:CS1') WHERE NGAY = '05-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV:KHMT:CS1') WHERE NGAY = '06-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV:KHMT:CS1,CS2') WHERE NGAY = '07-01-2024';

--
EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','THONGBAO');
BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
        policy_name => 'BRANCH_POLICY', 
        schema_name => 'C##ADMIN', 
        table_name => 'THONGBAO', 
        table_options => 'LABEL_DEFAULT, READ_CONTROL, WRITE_CONTROL'
    );
END;
/