-- Run with OLS_ADMIN --

--B18: VIẾT HÀM TẠO NHÃN
--drop FUNCTION GET_THONGBAO_LABEL;
--CREATE OR REPLACE FUNCTION GET_THONGBAO_LABEL ( 
--    P_VAITRO IN NVARCHAR2,
--    P_DONVI IN CHAR,
--    P_COSO IN VARCHAR 
--) 
--RETURN VARCHAR
--AS 
--    P_LABEL VARCHAR2(80); 
--BEGIN 
--    IF P_VAITRO = 'SV' THEN 
--        P_LABEL := 'SINHVIEN'; 
--    ELSIF P_VAITRO = 'NVCOBAN' THEN 
--        P_LABEL := 'NVCOBAN'; 
--    ELSIF P_VAITRO = 'GIAOVU' THEN 
--        P_LABEL := 'GIAOVU'; 
--    ELSIF P_VAITRO = 'GIANGVIEN' THEN 
--        P_LABEL := 'GIANGVIEN'; 
--    ELSIF P_VAITRO = 'TRUONGDV' THEN 
--        P_LABEL := 'TRUONGDV'; 
--    ELSIF P_VAITRO = 'TRUONGKHOA' THEN 
--        P_LABEL := 'TRUONGKHOA'; 
--    END IF; 
--    
--    IF P_DONVI = 'VPK' THEN 
--        P_LABEL := P_LABEL || ':VPK'; 
--    ELSIF P_DONVI = 'HTTT' THEN 
--        P_LABEL := P_LABEL || ':HTTT'; 
--    ELSIF P_DONVI = 'CNPM' THEN 
--        P_LABEL := P_LABEL || ':CNPM';
--    ELSIF P_DONVI = 'KHMT' THEN 
--        P_LABEL := P_LABEL || ':KHMT';
--    ELSIF P_DONVI = 'CNTT' THEN 
--        P_LABEL := P_LABEL || ':CNTT';
--    ELSIF P_DONVI = 'TGMT' THEN 
--        P_LABEL := P_LABEL || ':TGMT';
--    ELSIF P_DONVI = 'MMT' THEN 
--        P_LABEL := P_LABEL || ':MMT';
--    END IF; 
--    
--    IF P_COSO = 'CS1' THEN 
--        P_LABEL := P_LABEL || ':CS1'; 
--    ELSIF P_COSO = 'CS2' THEN 
--        P_LABEL := P_LABEL || ':CS2'; 
--    END IF; 
--    
--    RETURN CHAR_TO_LABEL('BRANCH_POLICY', P_LABEL); 
--END; 
--/ 
--SELECT GET_THONGBAO_LABEL('TRUONGKHOA', 'CNPM', 'CS1') FROM DUAL;
--SELECT CHAR_TO_LABEL('BRANCH_POLICY', 'SINHVIEN:CNTT:CS1') FROM DUAL; 
--/

BEGIN 
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','THONGBAO');
END;
/
BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY ( 
        policy_name => 'BRANCH_POLICY', 
        schema_name => 'C##ADMIN', 
        table_name => 'THONGBAO', 
        table_options => 'NO_CONTROL'
    ); 
END; 
/
DESC C##ADMIN.THONGBAO;


--B19: CẬP NHẬT NHÃN CHO CÁC DÒNG TRONG BẢNG (ĐANG DÙNG CẬP NHẬT THỦ CÔNG) 
ALTER SESSION SET nls_date_format='dd-mm-yyyy';
--UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = 'TRUONGKHOA' WHERE NGAY = '01-01-2024';
--UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = 'TRUONGDV:' WHERE NGAY = '02-01-2024';
--UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = 'TRUONGKHOA' WHERE NGAY = '03-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV') WHERE NGAY = '04-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'SINHVIEN:HTTT:CS1') WHERE NGAY = '05-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV:KHMT:CS1') WHERE NGAY = '06-01-2024';
UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV:KHMT:CS1,CS2') WHERE NGAY = '07-01-2024';
--UPDATE C##ADMIN.THONGBAO SET BRANCH_LABEL = 'TRUONGKHOA' WHERE NGAY = '08-01-2024';
/

BEGIN 
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','THONGBAO');
END;
/
BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY ( 
        policy_name => 'BRANCH_POLICY', 
        schema_name => 'C##ADMIN', 
        table_name => 'THONGBAO', 
        table_options => 'READ_CONTROL',
        predicate => NULL
    ); 
END; 
/