-- Chạy với SYS

-- Đăng nhập bằng C##ADMIN và bật audit_trail
ALTER SYSTEM SET AUDIT_TRAIL = DB,EXTENDED SCOPE = SPFILE;

-- Cho phép audit user sys
ALTER SYSTEM SET AUDIT_SYS_OPERATIONS = TRUE SCOPE = SPFILE;

-- Khởi động lại Instance
SHUTDOWN IMMEDIATE;
STARTUP;


-- Chạy với C##ADMIN

-- Tắt Standard Audit
NOAUDIT ALL ON C##ADMIN.DANGKY;
NOAUDIT ALL ON C##ADMIN.PHANCONG;
NOAUDIT ALL ON C##ADMIN.KHMO;
NOAUDIT ALL ON C##ADMIN.HOCPHAN;
NOAUDIT ALL ON C##ADMIN.DONVI;
NOAUDIT ALL ON C##ADMIN.NHANSU;
NOAUDIT ALL ON C##ADMIN.SINHVIEN;


-- Bật Standard Audit
AUDIT ALL ON C##ADMIN.DANGKY BY ACCESS;
AUDIT ALL ON C##ADMIN.PHANCONG BY ACCESS;
AUDIT ALL ON C##ADMIN.KHMO BY ACCESS;
AUDIT ALL ON C##ADMIN.HOCPHAN BY ACCESS;
AUDIT ALL ON C##ADMIN.DONVI BY ACCESS;
AUDIT ALL ON C##ADMIN.NHANSU BY ACCESS;
AUDIT ALL ON C##ADMIN.SINHVIEN BY ACCESS;
AUDIT ALL PROCEDURES;
AUDIT ALL FUNCTIONS;



--AUDIT SELECT, INSERT, UPDATE, DELETE ON table_name BY ACCESS;
--AUDIT EXECUTE PROCEDURE procedure_name BY ACCESS;
--AUDIT EXECUTE FUNCTION function_name BY ACCESS;



-- Thực hiện câu lệnh để kiểm tra
SELECT * FROM C##ADMIN.PHANCONG;


-- Kiểm tra nhật ký
SELECT USERNAME, EXTENDED_TIMESTAMP ,OBJ_NAME, ACTION_NAME,
    CASE RETURNCODE
    WHEN 0 THEN 'SUCCESSSFUL'
    WHEN 2004 THEN 'NOT SUCCESSFUL' END AS ACCESS_STATUS
FROM DBA_AUDIT_TRAIL
WHERE OBJ_NAME = 'PHANCONG';





