/*
 CS1 - Nh�n vi�n c� b?n
*/
-- CS1.1
-- T?o Policy function l?y Username c?a Sinh vi�n hi?n t?i
CREATE OR REPLACE FUNCTION POL_FUNC_CURRENT_USER_NHANSU (
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    -- Ki?m tra c� ph?i l� DBA kh�ng
    P_USER_ROLE := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF P_USER_ROLE = 'C##ADMIN' THEN
        RETURN '';
    END IF;
    
--    -- Ki?m tra role c?a c�c t�i kho?n c?n l?i
    SELECT GRANTED_ROLE INTO P_USER_ROLE
    FROM USER_ROLE_PRIVS 
    WHERE GRANTED_ROLE = 'RL_NVCOBAN' OR GRANTED_ROLE = 'RL_GIANGVIEN';
    IF P_USER_ROLE = 'RL_NVCOBAN' OR P_USER_ROLE = 'RL_GIANGVIEN' THEN
        RETURN 'MANV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
    ELSE
        RETURN '';
    END IF;
END;
/
-- Th�m ch�nh s�ch cho policy function POL_FUNC_CURRENT_USER_NHANSU
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'NHANSU',
        POLICY_NAME => 'POL_NHANSU_CURRENT_USER'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'NHANSU',
        POLICY_NAME => 'POL_NHANSU_CURRENT_USER',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_USER_NHANSU',
        STATEMENT_TYPES => 'SELECT, UPDATE',
        UPDATE_CHECK => TRUE
    );
END;
/
-- C?p quy?n tr�n b?ng NHANSU
GRANT SELECT ON NHANSU TO RL_NVCOBAN;
GRANT UPDATE (SDT) ON NHANSU TO RL_NVCOBAN;


-- CS1.2
-- C?p quy?n xem th�ng tin c?a t?t c? SINHVIEN, ��NV?, HOCPHAN, KHMO
GRANT SELECT ON SINHVIEN TO RL_NVCOBAN;
GRANT SELECT ON DONVI TO RL_NVCOBAN;
GRANT SELECT ON HOCPHAN TO RL_NVCOBAN;
GRANT SELECT ON KHMO TO RL_NVCOBAN;
/





/*
 CS2 - Gi?ng vi�n
*/

-- CS2.1
    GRANT SELECT ON NHANSU TO RL_GIANGVIEN;
    GRANT UPDATE (SDT) ON NHANSU TO RL_GIANGVIEN; 
    GRANT SELECT ON SINHVIEN TO RL_GIANGVIEN;
    GRANT SELECT ON DONVI TO RL_GIANGVIEN;
    GRANT SELECT ON HOCPHAN TO RL_GIANGVIEN;
    GRANT SELECT ON KHMO TO RL_GIANGVIEN;
-- CS2.2
-- T?o policy function l?y MANV c?a GIANGVIEN
CREATE OR REPLACE FUNCTION POL_FUNC_CURRENT_USER_PHANCONG (
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MAGV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'PHANCONG',
        POLICY_NAME => 'POL_NHANSU_CURRENT_GIANGVIEN',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_USER_PHANCONG',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
GRANT SELECT ON PHANCONG TO RL_GIANGVIEN;
-- CS2.3
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DANGKY',
        POLICY_NAME => 'POL_NHANSU_CURRENT_GIANGVIEN',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_USER_DANGKY',
        STATEMENT_TYPES => 'SELECT, UPDATE',
        UPDATE_CHECK => TRUE
    );
END;
/
GRANT SELECT ON DANGKY TO RL_GIANGVIEN;
-- CS2.4
GRANT UPDATE (DIEMTH, DIEMQT, DIEMCK, DIEMTK) ON DANGKY TO RL_GIANGVIEN;
/*
 CS3 - Gi�o v?
*/

-- CS3.1
GRANT SELECT ON DANGKY TO RL_NVCOBAN;
GRANT RL_NVCOBAN TO RL_GIAOVU;

SELECT *
FROM ALL_TAB_PRIVS
WHERE grantee = 'RL_GIAOVU';

-- CS3.2
GRANT SELECT, INSERT, UPDATE ON SINHVIEN TO RL_GIAOVU;
GRANT SELECT, INSERT, UPDATE ON DONVI TO RL_GIAOVU;
GRANT SELECT, INSERT, UPDATE ON HOCPHAN TO RL_GIAOVU;
GRANT SELECT, INSERT, UPDATE ON KHMO TO RL_GIAOVU;

-- CS3.3
-- Cấp quyền dữ liệu trên toàn bộ quan hệ PHANCONG
GRANT SELECT ON PHANCONG TO RL_GIAOVU;

--Tạo view 
CREATE OR REPLACE VIEW V_PHANCONG_RL_GIAOVU
AS
    SELECT PC.*
    FROM (PHANCONG PC JOIN HOCPHAN HP ON PC.MAHP = HP.MAHP)
    JOIN DONVI DV ON DV.MADV = HP.MADV
    WHERE DV.TENDV = 'Văn phòng khoa';

--Cấp quyền Update trên V_PHANCONG_RL_GIAOVU cho RL_GIAOVU
GRANT UPDATE ON V_PHANCONG_RL_GIAOVU TO RL_GIAOVU;

-- CS3.4
--Tạo view

CREATE OR REPLACE FUNCTION CONVERT_START_DANGKY_DATE (
    v_HK DANGKY.HK%TYPE,
    v_NAM DANGKY.NAM%TYPE
) RETURN DATE
AS
    v_START_MONTH VARCHAR2(2);
    v_DATE DATE;
BEGIN
    CASE v_HK
        WHEN 1 THEN v_START_MONTH := '01';
        WHEN 2 THEN v_START_MONTH := '05';
        WHEN 3 THEN v_START_MONTH := '09';
    END CASE;
    v_DATE:= TO_DATE('01' || '-' || v_START_MONTH || '-' || TO_CHAR(v_NAM), 'DD-MM-YYYY');
    RETURN v_DATE;
END;

CREATE OR REPLACE VIEW V_DANGKY_RL_GIAOVU
AS
    SELECT * FROM DANGKY
    WHERE SYSDATE - CONVERT_START_DANGKY_DATE(HK, NAM) <= 14 WITH CHECK OPTION;

GRANT INSERT ON V_DANGKY_RL_GIAOVU TO RL_GIAOVU;
GRANT DELETE ON V_DANGKY_RL_GIAOVU TO RL_GIAOVU;

--ALTER SESSION SET CURRENT_SCHEMA = c##ADMIN;
/*
    CS4: TRUONG DONVI
*/
-- CS4.1
GRANT RL_GIANGVIEN TO RL_TRUONGDV
/
-- CS4.2
CREATE OR REPLACE FUNCTION POL_FUNC_PHANCONG_TRUONGDV
(P_SCHEMA IN VARCHAR2, P_OBJECT  IN VARCHAR2)
RETURN VARCHAR2
IS
  v_condition VARCHAR2(200);
BEGIN
  v_condition := 'MAHP IN (SELECT MAHP FROM HOCPHAN WHERE MADV IN 
                  (SELECT MADV FROM ĐONVI WHERE TRUONGDV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
  RETURN v_condition;
END POL_FUNC_PHANCONG_TRUONGDV;
/

BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'C##ADMIN',
    object_name     => 'PHANCONG',
    policy_name     => 'V_HP_PHANCONG_TRUONGPHONG',
    policy_function => 'POL_FUNC_PHANCONG_TRUONGDV',
    statement_types => 'INSERT,UPDATE,DELETE',
    UPDATE_CHECK => TRUE
  );
END;
/
GRANT INSERT,UPDATE,DELETE ON PHANCONG TO RL_TRUONGDV;
/
--CS4.3
CREATE OR REPLACE FUNCTION POL_FUNC_PHANCONG_V_TRUONGDV
(P_SCHEMA IN VARCHAR2, P_OBJECT  IN VARCHAR2)
RETURN VARCHAR2
IS
  v_condition VARCHAR2(200);
BEGIN
  v_condition := 'MAGV IN (SELECT MANV FROM NHANSU WHERE MADV IN 
                  (SELECT MADV FROM ĐONVI WHERE TRUONGDV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
  RETURN v_condition;
END POL_FUNC_PHANCONG_V_TRUONGDV;

/

BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'C##ADMIN',
    object_name     => 'PHANCONG',
    policy_name     => 'V_GV_PHANCONG_TRUONGPHONG',
    policy_function => 'POL_FUNC_PHANCONG_V_TRUONGDV',
    statement_types => 'SELECT'
  );
END;
/
GRANT SELECT ON PHANCONG TO RL_TRUONGDV;
/
/*
    CS5: TRUONG KHOA
*/
-- CS5.1
GRANT RL_GIANGVIEN TO RL_TRUONGKHOA

/
-- CS5.2
CREATE OR REPLACE FUNCTION POL_FUNC_PHANCONG_TRUONGKHOA
(P_SCHEMA IN VARCHAR2, P_OBJECT  IN VARCHAR2)
RETURN VARCHAR2
IS
  v_condition VARCHAR2(200);
BEGIN
  v_condition := 'MAHP IN (SELECT MAHP FROM HOCPHAN WHERE MADV IN 
                  (SELECT MADV FROM DONVI WHERE TENDV = ''Văn phòng khoa'' ))';
  RETURN v_condition;
END POL_FUNC_PHANCONG_TRUONGKHOA;
/

BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'C##ADMIN',
    object_name     => 'PHANCONG',
    policy_name     => 'V_HP_PHANCONG_TRUONGKHOA',
    policy_function => 'POL_FUNC_PHANCONG_TRUONGKHOA',
    statement_types => 'INSERT,UPDATE,DELETE',
    UPDATE_CHECK => TRUE
  );
END;
/
GRANT INSERT,UPDATE,DELETE ON PHANCONG TO RL_TRUONGKHOA;
/
--CS5.3
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO RL_TRUONGKHOA;
GRANT SELECT ANY TABLE TO RL_TRUONGKHOA;




/*
 CS6 - Sinh vi�n
*/

-- CS6.1
-- T?o Policy function l?y Username c?a Sinh vi�n hi?n t?i
CREATE OR REPLACE FUNCTION POL_FUNC_CURRENT_USER_SINHVIEN (
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    -- Ki?m tra c� ph?i l� DBA kh�ng
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO P_USER_ROLE
    FROM DUAL;
    IF P_USER_ROLE = 'C##ADMIN' THEN
        RETURN '';
    END IF;
    
    -- Ki?m tra role c?a c�c t�i kho?n c?n l?i
    SELECT GRANTED_ROLE INTO P_USER_ROLE
    FROM USER_ROLE_PRIVS 
    WHERE GRANTED_ROLE = 'RL_SINHVIEN';
    IF P_USER_ROLE = 'RL_SINHVIEN' THEN
        RETURN 'MASV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
    ELSE
        RETURN '';
    END IF;
END;
/
-- Th�m ch�nh s�ch cho policy function POL_FUNC_CURRENT_USER_SINHVIEN
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'SINHVIEN',
        POLICY_NAME => 'POL_SINHVIEN_CURRENT_USER'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'SINHVIEN',
        POLICY_NAME => 'POL_SINHVIEN_CURRENT_USER',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_USER_SINHVIEN',
        STATEMENT_TYPES => 'SELECT, UPDATE',
        UPDATE_CHECK => TRUE
    );
END;
/
-- C?p quy?n tr�n b?ng SINHVIEN
GRANT SELECT ON SINHVIEN TO RL_SINHVIEN;
GRANT UPDATE (DCHI, SDT) ON SINHVIEN TO RL_SINHVIEN;

-- CS6.2
-- T?o Policy function l?y MANGANH c?a Sinh vi�n hi?n t?i
CREATE OR REPLACE FUNCTION POL_FUNC_CURRENT_MANGANH_SINHVIEN (
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) := '';
    P_SINHVIEN_MANGANH SINHVIEN.MANGANH%TYPE := '';
BEGIN
    -- Ki?m tra c� ph?i l� DBA kh�ng
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO P_USER_ROLE
    FROM DUAL;
    IF P_USER_ROLE = 'C##ADMIN' THEN
        RETURN '';
    END IF;
    
    -- Ki?m tra role c?a c�c t�i kho?n c?n l?i
    SELECT GRANTED_ROLE INTO P_USER_ROLE
    FROM USER_ROLE_PRIVS 
    WHERE GRANTED_ROLE = 'RL_SINHVIEN';
    IF P_USER_ROLE = 'RL_SINHVIEN' THEN
        SELECT MANGANH INTO P_SINHVIEN_MANGANH
        FROM SINHVIEN;
        RETURN 'MADV = ''' || P_SINHVIEN_MANGANH || '''';
    ELSE
        RETURN '';
    END IF;
END;
/
-- Th�m ch�nh s�ch cho policy function POL_FUNC_CURRENT_MANGANH_SINHVIEN
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOCPHAN',
        POLICY_NAME => 'POL_HOCPHAN_OF_MANGANH'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOCPHAN',
        POLICY_NAME => 'POL_HOCPHAN_OF_MANGANH',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_MANGANH_SINHVIEN',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
GRANT SELECT ON HOCPHAN TO RL_SINHVIEN;

-- T?o Policy function l?y MAHP c?a m?t ��n v?
CREATE OR REPLACE FUNCTION POL_FUNC_CURRENT_MAHP_HOCPHAN (
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) := '';
    P_HOCPHAN_LIST_MAHP VARCHAR2(5000) := '';
BEGIN
    -- Ki?m tra c� ph?i l� DBA kh�ng
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') INTO P_USER_ROLE
    FROM DUAL;
    IF P_USER_ROLE = 'C##ADMIN' THEN
        RETURN '';
    END IF;
    
    -- Ki?m tra role c?a c�c t�i kho?n c?n l?i
    SELECT GRANTED_ROLE INTO P_USER_ROLE
    FROM USER_ROLE_PRIVS 
    WHERE GRANTED_ROLE = 'RL_SINHVIEN';
    IF P_USER_ROLE = 'RL_SINHVIEN' THEN
        FOR c_row IN (SELECT MAHP FROM HOCPHAN) LOOP
        P_HOCPHAN_LIST_MAHP := P_HOCPHAN_LIST_MAHP || '''' || c_row.MAHP || ''', ';
        END LOOP;
        P_HOCPHAN_LIST_MAHP := RTRIM(P_HOCPHAN_LIST_MAHP, ', ');
        RETURN 'MAHP IN (' || P_HOCPHAN_LIST_MAHP || ')';
    ELSE
        RETURN '';
    END IF;
END;
/
-- Th�m ch�nh s�ch cho policy function POL_FUNC_CURRENT_MAHP_HOCPHAN
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'KHMO',
        POLICY_NAME => 'POL_KHMO_OF_MADV'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'KHMO',
        POLICY_NAME => 'POL_KHMO_OF_MADV',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_MAHP_HOCPHAN',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
GRANT SELECT ON KHMO TO RL_SINHVIEN;


-- CS6.3 ,6.4, 6.5
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DANGKY',
        POLICY_NAME => 'POL_DANGKY_CURRENT_USER'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DANGKY',
        POLICY_NAME => 'POL_DANGKY_CURRENT_USER',
        POLICY_FUNCTION => 'POL_FUNC_CURRENT_USER_SINHVIEN',
        STATEMENT_TYPES => 'SELECT, INSERT, UPDATE, DELETE',
        UPDATE_CHECK => TRUE
    );
END;
/
GRANT SELECT, INSERT, DELETE ON DANGKY TO RL_SINHVIEN;
