
/*
    DROP TABLE
*/
DROP TABLE TAILIEU CASCADE CONSTRAINTS PURGE;

/*
    CREATE TABLE
*/
CREATE TABLE TAILIEU
(
    MATL char(5) NOT NULL,
    TENTL NVARCHAR2(2000) NOT NULL
);

/*
    INSERT DATASET
*/
INSERT INTO TAILIEU VALUES ('TL001',  N'Kế hoạch phát triển Khoa');
INSERT INTO TAILIEU VALUES ('TL002',  N'Tài liệu dành cho Giáo Vụ');
INSERT INTO TAILIEU VALUES ('TL003',  N'Tài liệu dành cho Trưởng Đơn Vị');
--INSERT INTO TAILIEU VALUES ('TL004',  N'Tài liệu dành cho Sinh viên HTTT cơ sở 1');
INSERT INTO TAILIEU VALUES ('TL005',  N'Tài liệu dành cho Sinh viên cơ sở 1');


-- Run with C##ADMIN --
GRANT CREATE SESSION TO OLS_ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON TAILIEU TO OLS_ADMIN WITH GRANT OPTION;
/
GRANT SELECT ON C##ADMIN.TAILIEU TO RL_TRUONGKHOA, RL_TRUONGDV, RL_GIANGVIEN, RL_GIAOVU, RL_NVCOBAN, RL_SINHVIEN;
/
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'BRANCH_POLICY', label_tag => 622, label_value => 'SINHVIEN::CS1'); 
/

EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','TAILIEU');
EXECUTE SA_POLICY_ADMIN.APPLY_TABLE_POLICY (policy_name => 'BRANCH_POLICY', schema_name => 'C##ADMIN', table_name => 'TAILIEU', table_options => 'NO_CONTROL'); 
/
UPDATE C##ADMIN.TAILIEU SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGKHOA') WHERE MATL = 'TL001';
UPDATE C##ADMIN.TAILIEU SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV') WHERE MATL = 'TL003';
UPDATE C##ADMIN.TAILIEU SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'GIAOVU') WHERE MATL = 'TL002';
--UPDATE C##ADMIN.TAILIEU SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'SINHVIEN:HTTT:CS1') WHERE MATL = 'TL004';
UPDATE C##ADMIN.TAILIEU SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'SINHVIEN::CS1') WHERE MATL = 'TL005';

--
EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','TAILIEU');
BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
        policy_name => 'BRANCH_POLICY', 
        schema_name => 'C##ADMIN', 
        table_name => 'TAILIEU', 
        table_options => 'LABEL_DEFAULT, READ_CONTROL, WRITE_CONTROL'
    );
END;