-- Run with C##ADMIN --
/*
    DROP TABLE
*/
DROP TABLE DETAINC CASCADE CONSTRAINTS PURGE;

/*
    CREATE TABLE
*/
CREATE TABLE DETAINC
(
    MADETAI VARCHAR2(10) PRIMARY KEY,
    TIEUDE NVARCHAR2(100),
    NOIDUNG NVARCHAR2(2000)
);

/*
    INSERT DATASET
*/
INSERT INTO DETAINC VALUES ('DT_0000001',  N'Đề tài nghiên cứu 1 cấp khoa', N'Nội dung đề tài nghiên cứu cấp khoa');
INSERT INTO DETAINC VALUES ('DT_0000002',  N'Đề tài nghiên cứu 2 cấp khoa', N'Nội dung đề tài nghiên cứu cấp khoa');
INSERT INTO DETAINC VALUES ('DT_0000003',  N'Đề tài nghiên cứu của trưởng đơn vị HTTT cơ sở 1', N'Nội dung đề tài nghiên cứu của trưởng đơn vị HTTT cơ sở 1');
INSERT INTO DETAINC VALUES ('DT_0000004',  N'Đề tài nghiên cứu của trưởng đơn vị CNPM cơ sở 2', N'Nội dung đề tài nghiên cứu của trưởng đơn vị CNPM cơ sở 2');
INSERT INTO DETAINC VALUES ('DT_0000005',  N'Đề tài nghiên cứu của giảng viên bộ môn HTTT cơ sở 1', N'Nội dung đề tài nghiên cứu của giảng viên bộ môn HTTT cơ sở 1');
INSERT INTO DETAINC VALUES ('DT_0000006',  N'Đề tài nghiên cứu của sinh viên bộ môn HTTT cơ sở 1', N'Nội dung đề tài nghiên cứu sinh viên bộ môn HTTT cơ sở 1');

GRANT CREATE SESSION TO OLS_ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON DETAINC TO OLS_ADMIN WITH GRANT OPTION;

GRANT SELECT ON C##ADMIN.DETAINC TO RL_TRUONGKHOA, RL_TRUONGDV, RL_GIANGVIEN, RL_GIAOVU, RL_NVCOBAN, RL_SINHVIEN;

-- Run with OLS_ADMIN --

--Tao Label cho Data
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'BRANCH_POLICY', label_tag => 211, label_value => 'TRUONGDV:HTTT:CS1'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'BRANCH_POLICY', label_tag => 222, label_value => 'TRUONGDV:CNPM:CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'BRANCH_POLICY', label_tag => 311, label_value => 'GIANGVIEN:HTTT:CS1'); 



EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','DETAINC');
EXECUTE SA_POLICY_ADMIN.APPLY_TABLE_POLICY (policy_name => 'BRANCH_POLICY', schema_name => 'C##ADMIN', table_name => 'DETAINC', table_options => 'NO_CONTROL'); 

--B19: CẬP NHẬT NHÃN CHO CÁC DÒNG TRONG BẢNG (ĐANG DÙNG CẬP NHẬT THỦ CÔNG) 
UPDATE C##ADMIN.DETAINC SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGKHOA') WHERE MADETAI = 'DT_0000001';
UPDATE C##ADMIN.DETAINC SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGKHOA') WHERE MADETAI = 'DT_0000002';
UPDATE C##ADMIN.DETAINC SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV:HTTT:CS1') WHERE MADETAI = 'DT_0000003';
UPDATE C##ADMIN.DETAINC SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'TRUONGDV:CNPM:CS2') WHERE MADETAI = 'DT_0000004';
UPDATE C##ADMIN.DETAINC SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'GIANGVIEN:HTTT:CS1') WHERE MADETAI = 'DT_0000005';
UPDATE C##ADMIN.DETAINC SET BRANCH_LABEL = CHAR_TO_LABEL('BRANCH_POLICY', 'SINHVIEN:HTTT:CS1') WHERE MADETAI = 'DT_0000006';

--
EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_POLICY','C##ADMIN','DETAINC');

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
        policy_name => 'BRANCH_POLICY', 
        schema_name => 'C##ADMIN', 
        table_name => 'DETAINC', 
        table_options => 'LABEL_DEFAULT, READ_CONTROL, WRITE_CONTROL'
    );
END;
/
