--Lấy danh sách các role
CREATE OR REPLACE FUNCTION USP_GET_ROLE_NAME
RETURN SYS_REFCURSOR
AS
    P_ROLE_NAMES SYS_REFCURSOR;
BEGIN
    OPEN P_ROLE_NAMES FOR
        SELECT GRANTED_ROLE 
        FROM USER_ROLE_PRIVS 
        WHERE GRANTED_ROLE != 'DBA';
    RETURN P_ROLE_NAMES;
END;
/


-- Lấy các Role của User hoặc Role
CREATE OR REPLACE FUNCTION USP_GET_ROLE_PRIVILEGES(P_USER_ROLE IN VARCHAR2)
RETURN SYS_REFCURSOR
AS
    P_ROLE_PRIV SYS_REFCURSOR;
BEGIN
    OPEN P_ROLE_PRIV FOR
        SELECT GRANTEE, GRANTED_ROLE 
        FROM DBA_ROLE_PRIVS
        WHERE GRANTEE = P_USER_ROLE;
    RETURN P_ROLE_PRIV;
END;
/


-- Cấp Role 
CREATE OR REPLACE PROCEDURE USP_GRANT_ROLE(P_ROLE_NAME IN VARCHAR2, P_USER_ROLE IN VARCHAR2)
AS
BEGIN
    EXECUTE IMMEDIATE 'GRANT ' || P_ROLE_NAME || ' TO ' || P_USER_ROLE;
END;
/


-- Thu hồi Role
CREATE OR REPLACE PROCEDURE USP_REVOKE_ROLE(P_ROLE_NAME IN VARCHAR2, P_USER_ROLE IN VARCHAR2)
AS
    P_EXIST_ROLE VARCHAR2(20);
BEGIN
    SELECT GRANTED_ROLE INTO P_EXIST_ROLE
    FROM DBA_ROLE_PRIVS
    WHERE GRANTEE = P_USER_ROLE
    AND GRANTED_ROLE = P_ROLE_NAME;
    
    EXECUTE IMMEDIATE 'REVOKE ' || P_ROLE_NAME || ' FROM ' || P_USER_ROLE;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, N'Đối tượng không có Role này!');
END;
/