CREATE OR REPLACE FUNCTION USP_GET_USER_NAME 
RETURN SYS_REFCURSOR
AS
    P_USER_NAMES SYS_REFCURSOR;
BEGIN
    OPEN P_USER_NAMES  FOR
        SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE, CREATED, AUTHENTICATION_TYPE
        FROM DBA_USERS;
    RETURN P_USER_NAMES;
END;
/
CREATE OR REPLACE FUNCTION USP_GET_USER_NAME_LIST(p_user IN VARCHAR2)
RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE, CREATED, AUTHENTICATION_TYPE
        FROM DBA_USERS
        WHERE USERNAME LIKE '%' || UPPER(p_user) || '%'
        ORDER BY USERNAME;

    RETURN v_cursor;
END;
