CREATE OR REPLACE PROCEDURE USP_DETAINC_GETALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT TIEUDE, NOIDUNG
        FROM DETAINC;
END;
/
GRANT EXECUTE ON USP_DETAINC_GETALL TO PUBLIC;