CREATE OR REPLACE PROCEDURE USP_DONVI_GET_ALL (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM DONVI;
END;
/
GRANT EXECUTE ON USP_DONVI_GET_ALL TO RL_NVCOBAN;

CREATE OR REPLACE PROCEDURE USP_DONVI_GET_ALL_MADV (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT MADV
        FROM DONVI
        WHERE MADV != 'VPK';
END;
/
GRANT EXECUTE ON USP_DONVI_GET_ALL_MADV TO RL_NVCOBAN;