CREATE OR REPLACE PROCEDURE USP_GVU_PHANCONG_GETALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
WITH TMP AS
(SELECT MAHP AS MAHP FROM HOCPHAN WHERE MADV = (SELECT MADV FROM DONVI WHERE TENDV = N'Văn phòng khoa'))
SELECT PC.MAGV, PC.MAHP, H.TENHP ,PC.HK, PC.NAM, PC.MACT, 
NVL(TMP.MAHP, 'Không')
MAHP2
FROM PHANCONG PC LEFT JOIN TMP ON PC.MAHP = TMP.MAHP
JOIN HOCPHAN H ON PC.MAHP = H.MAHP
ORDER BY PC.NAM DESC, PC.HK DESC, PC.MACT, PC.MAGV, PC.MAHP;
END;
/
GRANT EXECUTE ON USP_GVU_PHANCONG_GETALL TO PUBLIC;/
CREATE OR REPLACE PROCEDURE USP_GVU_PHANCONG_SEARCH(P_KEYWORD IN VARCHAR2, P_RES OUT SYS_REFCURSOR)
AS
    V_KEYWORD VARCHAR2(100);
BEGIN
    V_KEYWORD := P_KEYWORD || '%';
    OPEN P_RES FOR
WITH TMP AS
(SELECT MAHP AS MAHP FROM HOCPHAN WHERE MADV = (SELECT MADV FROM DONVI WHERE TENDV = N'Văn phòng khoa'))
SELECT PC.MAGV, PC.MAHP, H.TENHP ,PC.HK, PC.NAM, PC.MACT, 
NVL(TMP.MAHP, 'Không')
MAHP2
FROM PHANCONG PC LEFT JOIN TMP ON PC.MAHP = TMP.MAHP
JOIN HOCPHAN H ON PC.MAHP = H.MAHP
WHERE PC.MAGV LIKE V_KEYWORD
ORDER BY PC.NAM DESC, PC.HK DESC, PC.MACT, PC.MAGV, PC.MAHP;
END;
/
GRANT EXECUTE ON USP_GVU_PHANCONG_SEARCH TO PUBLIC;
/
CREATE OR REPLACE PROCEDURE USP_GVU_PHANCONG_UPDATE (
 P_MAGV IN VARCHAR2,
   P_MAGV2 IN VARCHAR2,
    P_MAHP2 IN VARCHAR2,
  P_HK2 IN INT,
  P_NAM2 IN INT,
  P_MACT2 IN VARCHAR2,
  P_ErrCode OUT NUMBER
)
AS
BEGIN
  -- Insert with error handling
UPDATE PHANCONG
SET 
    MAGV = P_MAGV
WHERE
    MAGV = P_MAGV2 AND
     MAHP = P_MAHP2 AND
    HK = P_HK2 AND
    NAM = P_NAM2 AND
    MACT = P_MACT2;
  
  -- Handle potential errors during insert
   P_ErrCode := 0;
  EXCEPTION
    WHEN OTHERS THEN
      P_ErrCode := 1; -- Set error code to 1
      RETURN; -- Terminate procedure
END;
/
GRANT EXECUTE ON USP_GVU_PHANCONG_UPDATE TO RL_GIAOVU;
/
CREATE OR REPLACE PROCEDURE USP_GVU_PHANCONG_GET_ALL_MAGV(P_RES OUT SYS_REFCURSOR)
AUTHID DEFINER
AS
BEGIN
    OPEN P_RES FOR
        SELECT MANV AS MAGV
        FROM NHANSU;
END;
/
GRANT EXECUTE ON USP_GVU_PHANCONG_GET_ALL_MAGV TO PUBLIC;
/
-- DROP TRIGGER GVU_DANGKY_PHANCONG_CHANGE ;
CREATE OR REPLACE TRIGGER GVU_DANGKY_PHANCONG_CHANGE
BEFORE UPDATE  OF MAGV ON PHANCONG
FOR EACH ROW
DECLARE P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    SELECT USP_GET_USER_MAIN_ROLE INTO P_USER_ROLE   FROM DUAL;
    IF IS_ROLE_SUBROLE(P_USER_ROLE, 'RL_GIAOVU') = 'RL_GIAOVU' THEN
        UPDATE  DANGKY
        SET MAGV = :NEW.MAGV
        WHERE MAGV = :OLD.MAGV
        AND MAHP = :OLD.MAHP
        AND HK = :OLD.HK
        AND NAM = :OLD.NAM
        AND MACT = :OLD.MACT;
    END IF;
END;