CREATE OR REPLACE PROCEDURE USP_GET_DANG_KY_GV(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT DK.MASV, DK.MAGV, SV.HOTEN, DK.MAHP, HP.TENHP, DK.NAM ,DK.HK, DK.MACT, DK.DIEMTH, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
        FROM DANGKY DK
        JOIN SINHVIEN SV ON DK.MASV = SV.MASV
        JOIN HOCPHAN HP ON DK.MAHP = HP.MAHP ORDER BY DK.NAM DESC, DK.HK DESC, DK.MACT ASC, DK.MAHP ASC, DK.MASV DESC;
END;
/

CREATE OR REPLACE PROCEDURE USP_GET_DANG_KY_GV_SEARCH(P_RES OUT SYS_REFCURSOR, P_MASV IN VARCHAR2, P_MAGV IN VARCHAR2, P_MAHP IN VARCHAR2, P_NAM IN VARCHAR2, P_HK IN VARCHAR2, P_MACT IN VARCHAR2)
AS

    CONVERT_NAM INT;
    CONVERT_HK INT;

BEGIN
    CONVERT_NAM := to_number(P_NAM DEFAULT NULL ON CONVERSION ERROR);
    CONVERT_HK := to_number(P_HK DEFAULT NULL ON CONVERSION ERROR);
    OPEN P_RES FOR
        SELECT DK.MASV, DK.MAGV, SV.HOTEN, DK.MAHP, HP.TENHP, DK.HK, DK.NAM, DK.MACT, DK.DIEMTH, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
        FROM DANGKY DK
        JOIN SINHVIEN SV ON DK.MASV = SV.MASV
        JOIN HOCPHAN HP ON DK.MAHP = HP.MAHP
        WHERE (DK.MASV LIKE '%' || P_MASV || '%')
		AND (DK.MAGV LIKE '%' || P_MAGV || '%')
        AND (DK.MAHP LIKE '%' || P_MAHP || '%')
        AND (DK.NAM = CONVERT_NAM OR CONVERT_NAM IS NULL)
        AND (DK.HK = CONVERT_HK OR CONVERT_HK IS NULL)
        AND (DK.MACT LIKE '%' || P_MACT || '%' OR P_MACT IS NULL)
        ORDER BY DK.NAM DESC, DK.HK DESC, DK.MACT ASC, DK.MAHP ASC, DK.MASV DESC;
END;
/
GRANT EXECUTE ON USP_GET_DANG_KY_GV_SEARCH TO RL_GIANGVIEN;


CREATE OR REPLACE PROCEDURE USP_GV_UPDATE_DIEM(P_MASV IN VARCHAR2, P_MAGV IN VARCHAR2, P_MAHP IN VARCHAR2, P_HK IN INT, P_NAM IN INT, P_MACT IN VARCHAR2, P_DIEMTH IN FLOAT, P_DIEMQT IN FLOAT, P_DIEMCK IN FLOAT, P_DIEMTK IN FLOAT, P_CHECK OUT CHAR)
AS
    Old_DiemTK FLOAT;
    Temp_number INT;
    TinChiHP INT;
BEGIN
    SELECT DIEMTK INTO Old_DiemTK FROM DANGKY WHERE MASV = P_MASV AND MAGV = P_MAGV  AND HK = P_HK AND NAM = P_NAM AND MACT = CAST(P_MACT as CHAR(5)) AND MAHP = CAST(P_MAHP as CHAR(10));
    SELECT SOTCTL INTO Temp_number FROM SINHVIEN WHERE MASV = P_MASV;
    SELECT SOTC INTO TinChiHP FROM HOCPHAN WHERE MAHP = CAST(P_MAHP as CHAR(10));
    
    UPDATE DANGKY
    SET DIEMTH = P_DIEMTH,
        DIEMQT = P_DIEMQT,
        DIEMCK = P_DIEMCK,
        DIEMTK = P_DIEMTK
    WHERE MASV = P_MASV AND MAGV = P_MAGV  AND HK = P_HK AND NAM = P_NAM AND MACT = CAST(P_MACT as CHAR(5)) AND MAHP = CAST(P_MAHP as CHAR(10));
	P_CHECK := TO_CHAR(SQL%ROWCOUNT);
    
    IF (Old_DiemTK IS NOT NULL) THEN
        IF (Temp_number = TinChiHP) THEN
            UPDATE SINHVIEN
            SET DTBTL = P_DIEMTK
            WHERE MASV = P_MASV;
        ELSIF (P_DIEMTK > Old_DiemTK) THEN
            UPDATE SINHVIEN
            SET DTBTL = DTBTL + ((P_DIEMTK - Old_DiemTK) / SOTCTL)
            WHERE MASV = P_MASV;
        ELSIF (P_DIEMTK < Old_DiemTK) THEN
            UPDATE SINHVIEN
            SET DTBTL = DTBTL - ((Old_DiemTK - P_DIEMTK) / SOTCTL)
            WHERE MASV = P_MASV;
        END IF;
    ELSE
        IF (Temp_number = 0) THEN
            UPDATE SINHVIEN
            SET SOTCTL = SOTCTL + (SELECT SOTC FROM HOCPHAN WHERE MAHP = CAST(P_MAHP as CHAR(10)))
            WHERE MASV = P_MASV;
        
            UPDATE SINHVIEN
            SET DTBTL = P_DIEMTK
            WHERE MASV = P_MASV;
        ELSE
            UPDATE SINHVIEN
            SET SOTCTL = SOTCTL + (SELECT SOTC FROM HOCPHAN WHERE MAHP = CAST(P_MAHP as CHAR(10)))
            WHERE MASV = P_MASV;        
        
            UPDATE SINHVIEN
            SET DTBTL = (DTBTL*Temp_number + P_DIEMTK) / SOTCTL
            WHERE MASV = P_MASV;            
        END IF;
    END IF;     
END;
/



GRANT UPDATE(SOTCTL,DTBTL) ON SINHVIEN TO RL_GIANGVIEN;

GRANT EXECUTE ON USP_GV_UPDATE_DIEM TO RL_GIANGVIEN;
GRANT EXECUTE ON USP_GET_DANG_KY_GV TO RL_GIANGVIEN;
GRANT EXECUTE ON USP_GV_UPDATE_DIEM TO RL_TRUONGDV;
GRANT EXECUTE ON USP_GET_DANG_KY_GV TO RL_TRUONGDV;
