CREATE OR REPLACE PROCEDURE USP_GET_PHAN_CONG(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT HP.TENHP, PC.HK, PC.NAM, PC.MACT
        FROM PHANCONG PC JOIN HOCPHAN HP
        ON PC.MAHP = HP.MAHP;
END;
/
GRANT EXECUTE ON USP_GET_PHAN_CONG TO RL_GIANGVIEN;
GRANT EXECUTE ON USP_GET_PHAN_CONG TO RL_TRUONGDV;

