CREATE OR REPLACE PROCEDURE USP_GET_PHAN_CONG(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        WITH CTE AS
    (
      SELECT MANV, HOTEN FROM NHANSU
    )
        SELECT PC.MAGV, CTE.HOTEN, HP.TENHP, PC.MAHP, PC.HK, PC.NAM, PC.MACT
        FROM PHANCONG PC JOIN HOCPHAN HP
        ON PC.MAHP = HP.MAHP JOIN CTE ON PC.MAGV = CTE.MANV ORDER BY PC.NAM DESC, PC.HK DESC;
END;
/
GRANT EXECUTE ON USP_GET_PHAN_CONG TO RL_GIANGVIEN;
GRANT EXECUTE ON USP_GET_PHAN_CONG TO RL_TRUONGDV;

