CREATE OR REPLACE PROCEDURE USP_HOCPHAN_GETALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM HOCPHAN;
END;
/
GRANT EXECUTE ON USP_HOCPHAN_GETALL TO PUBLIC;



CREATE OR REPLACE PROCEDURE USP_HOCPHAN_SEARCH(P_KEYWORD IN VARCHAR2, P_RES OUT SYS_REFCURSOR)
AS
    V_KEYWORD VARCHAR2(100);
BEGIN
    V_KEYWORD := P_KEYWORD || '%';
    OPEN P_RES FOR
        SELECT *
        FROM HOCPHAN
        WHERE MAHP LIKE V_KEYWORD
        OR MADV LIKE V_KEYWORD;
END;
/
GRANT EXECUTE ON USP_HOCPHAN_SEARCH TO PUBLIC;