CREATE OR REPLACE PROCEDURE USP_KETQUAHP_GET_ALL_NAM_HK(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT DISTINCT NAM, HK
        FROM DANGKY
        ORDER BY NAM DESC, HK DESC;
END;
/
GRANT EXECUTE ON USP_KETQUAHP_GET_ALL_NAM_HK TO PUBLIC;
/



CREATE OR REPLACE PROCEDURE USP_KETQUAHP_GET_ALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT (DK.HK || ' - ' || DK.NAM) AS HK_NAM, DK.MAHP, HP.TENHP,
        HP.SOTC, DK.MAGV, DK.DIEMTH, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
        FROM DANGKY DK JOIN HOCPHAN HP
        ON DK.MAHP = HP.MAHP
        ORDER BY HK_NAM DESC;
END;
/
GRANT EXECUTE ON USP_KETQUAHP_GET_ALL TO PUBLIC;
/



CREATE OR REPLACE PROCEDURE USP_KETQUAHP_GET_BY_NAM_HK(
    P_RES OUT SYS_REFCURSOR,
    P_NAM IN NUMBER,
    P_HK IN NUMBER)
AS
BEGIN
    OPEN P_RES FOR
        SELECT (DK.HK || ' - ' ||  DK.NAM) AS HK_NAM, DK.MAHP, HP.TENHP,
        HP.SOTC, DK.MAGV, DK.DIEMTH, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
        FROM DANGKY DK JOIN HOCPHAN HP
        ON DK.MAHP = HP.MAHP
        WHERE DK.NAM = P_NAM AND DK.HK = P_HK;
END;
/
GRANT EXECUTE ON USP_KETQUAHP_GET_BY_NAM_HK TO PUBLIC;
/