CREATE OR REPLACE PROCEDURE USP_KHMO_GETALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT KHMO.HK, KHMO.NAM, HP.MADV, HP.TENHP, HP.MAHP, HP.SOTC
        FROM KHMO JOIN HOCPHAN HP
        ON KHMO.MAHP = HP.MAHP
        ORDER BY NAM DESC, HK DESC, HP.MADV, HP.MAHP;
END;
/
GRANT EXECUTE ON USP_KHMO_GETALL TO PUBLIC;




CREATE OR REPLACE PROCEDURE USP_KHMO_GET_BY_NAM_HK(
    P_RES OUT SYS_REFCURSOR,
    P_NAM IN NUMBER,
    P_HK IN NUMBER
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT KHMO.HK, KHMO.NAM, HP.MADV, HP.TENHP, HP.MAHP, HP.SOTC
        FROM KHMO JOIN HOCPHAN HP
        ON KHMO.MAHP = HP.MAHP
        WHERE KHMO.NAM = P_NAM AND KHMO.HK = P_HK
        ORDER BY NAM DESC, HK DESC, HP.MADV, HP.MAHP;
END;
/
GRANT EXECUTE ON USP_KHMO_GET_BY_NAM_HK TO PUBLIC;




CREATE OR REPLACE PROCEDURE USP_KHMO_GET_ALL_NAM_HK(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT DISTINCT NAM, HK
        FROM KHMO
        ORDER BY NAM DESC, HK DESC;
END;
/
GRANT EXECUTE ON USP_KHMO_GET_ALL_NAM_HK TO PUBLIC;