CREATE OR REPLACE PROCEDURE USP_NHANSU_GET_PROFILE (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM NHANSU
        WHERE MANV = SYS_CONTEXT ('USERENV', 'SESSION_USER');
END;
/
GRANT EXECUTE ON USP_NHANSU_GET_PROFILE TO RL_NVCOBAN;

CREATE OR REPLACE PROCEDURE USP_NHANSU_UPDATE_SDT_PROFILE (P_SDT IN CHAR)
AS
BEGIN
    UPDATE NHANSU
    SET SDT = P_SDT
    WHERE MANV = SYS_CONTEXT ('USERENV', 'SESSION_USER');
END;
/
GRANT EXECUTE ON USP_NHANSU_UPDATE_SDT_PROFILE TO RL_NVCOBAN;

CREATE OR REPLACE PROCEDURE USP_NHANSU_GET_GIANGVIEN (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT MANV as MAGV, HOTEN, SDT, MADV, COSO
        FROM NHANSU
        WHERE VAITRO = 'Giảng viên';
END;
/
GRANT EXECUTE ON USP_NHANSU_GET_GIANGVIEN TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_NHANSU_GET_ALL (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM NHANSU;
END;
/
GRANT EXECUTE ON USP_NHANSU_GET_ALL TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_NHANSU_INSERT  
(
    vMANV IN CHAR, vHOTEN IN NVARCHAR2, 
    vPHAI IN NVARCHAR2, vNGSINH IN DATE, 
    vPHUCAP IN FLOAT, vSDT IN CHAR, 
    vVAITRO IN NVARCHAR2, vMADV IN CHAR, vCOSO IN CHAR
)
AUTHID DEFINER
AS
BEGIN
    INSERT INTO NHANSU
    VALUES (vMANV, vHOTEN, vPHAI, vNGSINH, vPHUCAP, vSDT, vVAITRO, vMADV, vCOSO);
    
    USP_CREATE_USER(vMANV, vMANV);
    
    IF vVAITRO = N'Nhân viên cơ bản' THEN 
            EXECUTE IMMEDIATE ('GRANT RL_NVCOBAN TO ' || vMANV);
        ELSIF vVAITRO = N'Giảng viên' THEN
            EXECUTE IMMEDIATE ('GRANT RL_GIANGVIEN TO ' || vMANV);
        ELSIF vVAITRO = N'Giáo vụ' THEN
            EXECUTE IMMEDIATE ('GRANT RL_GIAOVU TO ' || vMANV);
        ELSIF vVAITRO = N'Trưởng đơn vị' THEN
            EXECUTE IMMEDIATE ('GRANT RL_TRUONGDV TO ' || vMANV);
        ELSIF vVAITRO = N'Trưởng khoa' THEN
            EXECUTE IMMEDIATE ('GRANT RL_TRUONGKHOA TO ' || vMANV);
        END IF;
END;
/

GRANT EXECUTE ON USP_NHANSU_INSERT TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_NHANSU_UPDATE
(
    vMANV IN CHAR, vHOTEN IN NVARCHAR2, 
    vPHAI IN NVARCHAR2, vNGSINH IN DATE, 
    vPHUCAP IN FLOAT, vSDT IN CHAR, 
    vVAITRO IN NVARCHAR2, vMADV IN CHAR, vCOSO IN CHAR
)
AS
BEGIN
    UPDATE NHANSU
    SET HOTEN = vHOTEN, PHAI = vPHAI, NGSINH = vNGSINH, 
    PHUCAP = vPHUCAP, SDT = vSDT, VAITRO = vVAITRO, MADV = vMADV, COSO = vCOSO
    WHERE MANV = vMANV;
END;
/
GRANT EXECUTE ON USP_NHANSU_UPDATE TO RL_TRUONGKHOA;


CREATE OR REPLACE PROCEDURE USP_NHANSU_DELETE (vMANV IN CHAR)
AS
BEGIN
    DELETE FROM NHANSU
    WHERE MANV = vMANV;
END;
/
GRANT EXECUTE ON USP_NHANSU_DELETE TO RL_TRUONGKHOA;