CREATE OR REPLACE PROCEDURE USP_PHANCONG_TRUONGKHOA_GET_ALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT PHANCONG.*, HOCPHAN.MADV
        FROM PHANCONG JOIN HOCPHAN ON PHANCONG.MAHP = HOCPHAN.MAHP;
END;
/
GRANT EXECUTE ON USP_PHANCONG_TRUONGKHOA_GET_ALL TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_PHANCONG_DELETE(vMAGV IN CHAR, vMAHP IN CHAR, vHK IN NUMBER, vNAM IN NUMBER, vMACT IN CHAR, vDeleteCount OUT CHAR)
AS
BEGIN
    DELETE FROM PHANCONG
    WHERE MAGV = vMAGV AND MAHP = vMAHP AND HK = vHK AND NAM = vNAM AND MACT = vMACT;
    
    vDeleteCount := TO_CHAR(SQL%ROWCOUNT);
END;
/
GRANT EXECUTE ON USP_PHANCONG_DELETE TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_PHANCONG_THEM(vMAGV IN CHAR, vMAHP IN CHAR, vHK IN NUMBER, vNAM IN NUMBER, vMACT IN CHAR)
AS
BEGIN
    INSERT INTO PHANCONG
    VALUES(vMAGV, vMAHP, vHK, vNAM, vMACT);
END;
/
GRANT EXECUTE ON USP_PHANCONG_THEM TO RL_TRUONGKHOA;

