CREATE OR REPLACE PROCEDURE USP_PHANCONG_TRUONGKHOA_GET_ALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT PHANCONG.*, HOCPHAN.MADV
        FROM PHANCONG JOIN HOCPHAN ON PHANCONG.MAHP = HOCPHAN.MAHP
        ORDER BY PHANCONG.NAM DESC, PHANCONG.HK DESC, PHANCONG.MACT, PHANCONG.MAHP, PHANCONG.MAGV;
END;
/
GRANT EXECUTE ON USP_PHANCONG_TRUONGKHOA_GET_ALL TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_PHANCONG_DELETE(vMAGV IN CHAR, vMAHP IN CHAR, vHK IN NUMBER, vNAM IN NUMBER, vMACT IN CHAR, vDeleteCount OUT CHAR)
AS
BEGIN
    DELETE FROM PHANCONG
    WHERE MAGV = vMAGV AND MAHP = vMAHP AND HK = vHK AND NAM = vNAM AND MACT = vMACT;
    
    vDeleteCount := TO_CHAR(SQL%ROWCOUNT);
END;
/
GRANT EXECUTE ON USP_PHANCONG_DELETE TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_PHANCONG_THEM(vMAGV IN CHAR, vMAHP IN CHAR, vHK IN NUMBER, vNAM IN NUMBER, vMACT IN CHAR)
AS
BEGIN
    INSERT INTO PHANCONG
    VALUES(vMAGV, vMAHP, vHK, vNAM, vMACT);
END;
/
GRANT EXECUTE ON USP_PHANCONG_THEM TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_PHANCONG_CHECK_DANGKY(
    vMAGV IN CHAR,
    vMAHP IN CHAR,
    vHK IN NUMBER,
    vNAM IN NUMBER,
    vMACT IN CHAR
)
AS
    rNum NUMBER;
BEGIN
    SELECT COUNT(*) INTO rNum
    FROM DANGKY
    WHERE MAGV = vMAGV AND MAHP = vMAHP AND HK = vHK AND NAM = vNAM AND MACT = vMACT;
    
    IF rNUM != 0
    THEN
        RAISE_APPLICATION_ERROR(-20001,'');
    END IF;
END;
/
GRANT EXECUTE ON USP_PHANCONG_CHECK_DANGKY TO RL_TRUONGKHOA;

CREATE OR REPLACE PROCEDURE USP_PHANCONG_CHANGE_MAGV(
    vMAGV IN CHAR,
    vMAHP IN CHAR,
    vHK IN NUMBER,
    vNAM IN NUMBER,
    vMACT IN CHAR,
    vMAGVNEW IN CHAR
)
AS
    vCount NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO vCount
    FROM PHANCONG
    WHERE MAGV = vMAGVNEW AND MAHP = vMAHP AND HK = vHK AND NAM = vNAM AND MACT = vMACT;
    
    IF vCount > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Giáo viên đã được phân công cho kế hoạch mở này');
    END IF;
        
    UPDATE PHANCONG
    SET MAGV = vMAGVNEW
    WHERE MAGV = vMAGV AND MAHP = vMAHP AND HK = vHK AND NAM = vNAM AND MACT = vMACT;
    
    IF SQL%ROWCOUNT = 0
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'Phân công chứa học phần không thuộc quản lý của Văn Phòng Khoa');
    END IF;
    
    EXCEPTION
       WHEN OTHERS THEN
          DELETE FROM PHANCONG
          WHERE MAGV = vMAGV;
          INSERT INTO PHANCONG
          VALUES (vMAGVNEW, vMAHP, vHK, vNAM, vMACT);
    COMMIT;
END;
/
GRANT EXECUTE ON USP_PHANCONG_CHANGE_MAGV TO RL_TRUONGKHOA;