CREATE OR REPLACE PROCEDURE USP_SINHVIEN_GET_PROFILE (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM SINHVIEN
        WHERE MASV = SYS_CONTEXT ('USERENV', 'SESSION_USER');
END;
/
GRANT EXECUTE ON USP_SINHVIEN_GET_PROFILE TO RL_SINHVIEN;



CREATE OR REPLACE PROCEDURE USP_SINHVIEN_UPDATE_SDT_PROFILE (P_SDT IN VARCHAR2)
AS
BEGIN
    UPDATE SINHVIEN
    SET SDT = P_SDT
    WHERE MASV = SYS_CONTEXT ('USERENV', 'SESSION_USER');
END;
/
GRANT EXECUTE ON USP_SINHVIEN_UPDATE_SDT_PROFILE TO RL_SINHVIEN;


CREATE OR REPLACE PROCEDURE USP_SINHVIEN_GET_ALL (P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM SINHVIEN;
END;
/
GRANT EXECUTE ON USP_SINHVIEN_GET_ALL TO RL_NVCOBAN;






