-- Kiểm tra quyền theo Table
CREATE OR REPLACE PROCEDURE USP_GET_PRIVS_USER_ROLE_TAB
(
    V_USER_ROLE IN VARCHAR2,
    CHOICE IN VARCHAR2,
    CUR_TAB_PRIVS_USER OUT SYS_REFCURSOR,
    CUR_TAB_PRIVS_ROLE OUT SYS_REFCURSOR
)
AS
BEGIN
    IF CHOICE = 'ROLE'
    THEN
        OPEN CUR_TAB_PRIVS_ROLE FOR
            SELECT GRANTEE, TABLE_NAME, PRIVILEGE, GRANTOR, GRANTABLE
            FROM USER_TAB_PRIVS
            WHERE GRANTEE = UPPER(V_USER_ROLE)
            OR GRANTEE IN (
                SELECT DISTINCT GRANTED_ROLE
                FROM   ROLE_ROLE_PRIVS RP
                CONNECT BY PRIOR RP.GRANTED_ROLE = RP.ROLE
                START WITH RP.ROLE = UPPER(V_USER_ROLE)
              )
            ORDER BY TABLE_NAME;
    ELSE
        OPEN CUR_TAB_PRIVS_USER FOR
            SELECT u.GRANTEE, TABLE_NAME, PRIVILEGE, GRANTOR, GRANTABLE
            FROM USER_TAB_PRIVS u
            WHERE u.GRANTEE = UPPER(V_USER_ROLE)
            UNION ALL
            SELECT u.GRANTEE, TABLE_NAME, PRIVILEGE, GRANTOR, GRANTABLE
            FROM USER_TAB_PRIVS u
            INNER JOIN DBA_ROLE_PRIVS d ON u.GRANTEE = d.GRANTED_ROLE
            WHERE d.GRANTEE = UPPER(V_USER_ROLE);
    END IF;
END;
/
-- Kiểm tra quyền theo Col
CREATE OR REPLACE PROCEDURE USP_GET_PRIVS_USER_ROLE_COL
(
    V_USER_ROLE IN VARCHAR2,
    CHOICE IN VARCHAR2,
    CUR_COL_PRIVS_USER OUT SYS_REFCURSOR,
    CUR_COL_PRIVS_ROLE OUT SYS_REFCURSOR
)
AS
BEGIN
    IF CHOICE = 'ROLE'
    THEN
        OPEN CUR_COL_PRIVS_ROLE FOR
            SELECT GRANTEE, TABLE_NAME, COLUMN_NAME, PRIVILEGE, GRANTOR, GRANTABLE
            FROM USER_COL_PRIVS
            WHERE GRANTEE = 'RL_TRUONGKHOA'
            OR GRANTEE IN (
                SELECT DISTINCT GRANTED_ROLE
                FROM   ROLE_ROLE_PRIVS RP
                CONNECT BY PRIOR RP.GRANTED_ROLE = RP.ROLE
                START WITH RP.ROLE = 'RL_TRUONGKHOA'
              )
            ORDER BY TABLE_NAME;
    ELSE
        OPEN CUR_COL_PRIVS_USER FOR
            SELECT u.GRANTEE, TABLE_NAME, COLUMN_NAME, PRIVILEGE, GRANTOR, GRANTABLE
            FROM USER_COL_PRIVS u
            WHERE u.GRANTEE = UPPER(V_USER_ROLE)
            UNION ALL
            SELECT u.GRANTEE, TABLE_NAME, COLUMN_NAME, PRIVILEGE, GRANTOR, GRANTABLE
            FROM USER_COL_PRIVS u
            INNER JOIN DBA_ROLE_PRIVS d ON u.GRANTEE = d.GRANTED_ROLE
            WHERE d.GRANTEE = UPPER(V_USER_ROLE);
    END IF;
END;
/
CREATE OR REPLACE PROCEDURE USP_GET_USER 
(
    CUR_USER OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CUR_USER FOR
        SELECT USERNAME
        FROM DBA_USERS
        WHERE USERNAME LIKE 'SV%' OR USERNAME LIKE 'NV%';
END;
/

