CREATE OR REPLACE FUNCTION USP_GET_USER_LIST(p_user IN VARCHAR2)
RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT USERNAME
        FROM DBA_USERS
        WHERE USERNAME LIKE '%' || UPPER(p_user) || '%';

    RETURN v_cursor;
END;
/
GRANT EXECUTE ON USP_GET_USER_LIST TO PUBLIC;

CREATE OR REPLACE FUNCTION USP_GET_ROLE_LIST(p_role IN VARCHAR2)
RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT ROLE
        FROM DBA_ROLES
        WHERE ROLE LIKE UPPER(p_role) || '%';

    RETURN v_cursor;
END;
/
GRANT EXECUTE ON USP_GET_USER_LIST TO PUBLIC;

CREATE OR REPLACE PROCEDURE USP_CREATE_USER (
    SP_USERNAME IN VARCHAR2,
    SP_PASSWORD IN VARCHAR2
)
AS
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ' || SP_USERNAME || ' IDENTIFIED BY ' || SP_PASSWORD;
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || SP_USERNAME;
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ' || SP_USERNAME;
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ' || SP_USERNAME;
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ' || SP_USERNAME;
END;
/

GRANT EXECUTE ON USP_CREATE_USER TO PUBLIC;